/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 *
 * It mirrors the application tables currently visible in Neon so Kysely can
 * type-check table names, columns, inserts, updates, and query results.
 * Regenerate it after Neon schema changes with `pnpm db:types`.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

// Represents the externally managed Neon table used by admin authentication.
export interface AdminCredentials {
  created_at: Generated<Timestamp>;
  email: string;
  password_hash: string;
  singleton_key: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

// Maps database table names to their generated row types for Kysely.
export interface DB {
  admin_credentials: AdminCredentials;
}
